# Generated by Django 3.2.16 on 2023-01-20 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Divisi",
            fields=[
                ("divisi_id", models.AutoField(primary_key=True, serialize=False)),
                ("kode", models.CharField(max_length=15)),
                ("nama", models.CharField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
            ],
            options={
                "verbose_name_plural": "divisi",
                "db_table": "divisi",
            },
        ),
        migrations.CreateModel(
            name="Karyawan",
            fields=[
                ("karyawan_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_karyawan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "divisi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="karyawan_divisi",
                        to="karyawan.divisi",
                    ),
                ),
                ("noinduk", models.CharField(max_length=20)),
                ("nama", models.CharField(max_length=150)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
            ],
            options={
                "verbose_name_plural": "karyawan",
                "db_table": "karyawan",
                "ordering": ["created"],
            },
        ),
    ]
