# Generated by Django 3.2.17 on 2023-02-16 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karyawan',
            options={'ordering': ['nama'], 'verbose_name_plural': 'karyawan'},
        ),
    ]
