version: "3.8"
services:
  app:
    image: skripsi-be:v1.0.2
    restart: unless-stopped
    ports:
      - "8080:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    env_file:
      - .prod.env
    networks:
      - backend
    user: "aplikasi:aplikasi"
    volumes:
      - ./storage/:/app/storage

  web:
    image: nginx:stable-alpine
    restart: unless-stopped
    env_file:
      - .prod.env
    networks:
      - backend
      - proxy
    ports:
      - "81:80"
    volumes:
      - ./storage/staticfiles:/app/storage/staticfiles
      - ./storage/media:/app/storage/media
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

    labels:
      - "traefik.enable=true"
      # beri nama router unik, entrypoint ambil dari traefik.yml
      - "traefik.http.routers.${TR_APP}-secure.entrypoints=https"
      # beri nama router unik & tentukan domain atau pathnya
      - "traefik.http.routers.${TR_APP}-secure.rule=Host(`${DOMAIN}`)"
      # jika pakai path, uncomment baris dibawah ini
      # - "traefik.http.routers.${TR_APP}-secure.rule=Host(`${DOMAIN}`) && PathPrefix(`/${TR_PATH}`)"
      # servicename ini, samakan dengan baris dibawah ini
      - "traefik.http.routers.${TR_APP}-secure.service=${TR_APP}-secure"
      # ya, servicename yg ini, begitupun port yang di-expose
      - "traefik.http.services.${TR_APP}-secure.loadbalancer.server.port=${TR_PORT}"
      - "traefik.http.routers.${TR_APP}-secure.tls=true"

networks:
  backend:
    external: true
  proxy:
    external: true
