# Generated by Django 3.2.16 on 2023-01-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('presensi_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='presensi_karyawan', to='karyawan.karyawan')),
                ('tanggal', models.DateField()),
                ('waktu_hadir', models.TimeField(blank=True, null=True)),
                ('waktu_pulang', models.TimeField(blank=True, null=True)),
                ('jenis', models.CharField(choices=[('IN', 'Datang'), ('OUT', 'Pulang')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'presensi',
                'db_table': 'presensi',
                'ordering': ['karyawan_id', 'created'],
            },
        ),
    ]
