# Generated by Django 3.2.16 on 2023-01-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitraWajah',
            fields=[
                ('citrawajah_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='citra_karyawan', to='karyawan.karyawan')),
                ('nama', models.ImageField(upload_to='faces/', verbose_name='Citra Wajah')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'citra wajah',
                'db_table': 'citrawajah',
                'ordering': ['karyawan_id', 'created'],
            },
        ),
    ]
